name: application_map_todolist
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # แพ็กเกจ Cupertino Icons ให้ไอคอนแบบ iOS
  google_maps_flutter: ^2.6.1 # แพ็กเกจแสดง Google Maps รองรับทั้ง Android และ iOS
  geolocator: ^13.0.1 # แพ็กเกจเข้าถึง ตำแหน่ง Location และ GPS ของอุปกรณ์
  geocoding: ^3.0.0 # แพ็กเกจแปลงพิกัดละติจูดและลองจิจูดเป็นที่อยู่
  http: ^1.2.1
  flutter_polyline_points: ^2.0.0 # แพ็กเกจรสร้าง Polyline บน Google Maps
  syncfusion_flutter_calendar: ^20.3.47 # แพ็กเก็ตแสดงปฏิทิน
  intl: ^0.19.0 # Intl สําหรับการแปลภาษาและการตั้งค่าท้องถิ่น
  provider: ^6.1.2 # แพ็กเกจการจัดการสถานะ
  shared_preferences: ^2.2.3 # แพ็กเกจเก็บข้อมูลแบบถาวรบนอุปกรณ์
  flutter_local_notifications: ^18.0.1 # แพ็กเก็ตแสดงการแจ้งเตือนบนอุปกรณ์มือถือ
  path_provider: ^2.0.12 # Path provider สําหรับค้นหาตําแหน่งที่ใช้บ่อยในระบบไฟล์
  permission_handler: ^10.2.0 # แพ็กเก็ตขอสิทธิ์ permissions บนอุปกรณ์มือถือ
  json_annotation: ^4.8.0 # แพ็กเก็ตใช้ในการทำงานกับ JSON
  json_serializable: ^6.6.0 # แพ็กเก็ตช่อยในการแปลงข้อมูลระหว่างรูปแบบของ Object กับ JSON โดยอัตโนมัติ
  build_runner: ^2.3.3 # แพ็กเก็ตสร้างไฟล์อัตโนมัติจากโค้ดที่เขียน
  file_picker: ^8.3.3 # แพ็กเก็ตเลือกไฟล์จากอุปกรณ์ของผู้ใช้
  image_picker: ^1.1.2 # แพ็กเกจเลือกหรือถ่ายรูปจากแกลเลอรี
  fluttertoast: ^8.0.9 # แพ็กเก็ตแสดงข้อความแบบ Toast บนหน้าจอ
  flutter_file_dialog: ^3.0.2 # แพ็กเก็ตใช้สำหรับการเลือกไฟล์จากไฟล์ระบบของอุปกรณ์หรือการบันทึกไฟล์
  pin_code_fields: ^8.0.1 # แพ็กเก็ตสร้างฟิลด์การป้อนรหัสผ่านแบบ Pin
  flutter_localization: ^0.3.1 # แพ็กเก็ตรองรับการแปลภาษาในแอปพลิเคชัน
  hive: ^2.2.3 # แพ็กเก็ตจัดเก็บข้อมูลในฐานข้อมูล NoSQL ภายในแอปพลิเคชันโดยไม่ต้องใช้เซิร์ฟเวอร์หรือการเชื่อมต่ออินเทอร์เน็ต
  hive_flutter: ^1.1.0 # แพ็กเก็ตเก็บข้อมูลในฐานข้อมูลแบบ NoSQL ในรูปแบบของ Box
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.0
  hive_generator: ^2.0.1
flutter:
  uses-material-design: true
  fonts:
  - family: PixelFont
    fonts:
      - asset: assets/fonts/pixel_font.ttf
  assets:
    - assets/
    - assets/setting/
    - assets/image_list/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
